{{- $sel := dict "root" . "component" "frontend" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incidents.fullname" . }}-frontend
  labels:
    {{- include "incidents.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "incidents.selectorLabels" $sel | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incidents.selectorLabels" $sel | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: frontend
          image: {{ include "incidents.image" (dict "name" "frontend" "values" .Values.frontend) }}
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          env:
            - name: BACKEND_HOST
              value: {{ include "incidents.fullname" . }}-backend
          readinessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 15
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: [ALL]}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incidents.fullname" . }}-frontend
  labels:
    {{- include "incidents.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "incidents.selectorLabels" $sel | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
