apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incidents.fullname" . }}-db
  labels:
    {{- include "incidents.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s-postgres:5432/%s" .Values.postgres.username .Values.postgres.password (include "incidents.fullname" .) .Values.postgres.database | quote }}
